name: coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: xdebug
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - run: docker run -d -p 4222:4222 nats --js
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          args: tests
