name: coverage
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - run: docker run -d -p 4222:4222 nats --js
      - run: pecl install xdebug && php -v
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          args: tests
