name: phpunit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NATS_CLIENT_LOG: 1
      NATS_TEST_LOG: 1
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          args: tests
    services:
      nats:
        image: nats
        command:
          - '-js'
        ports:
          - '4222:4222'